### ISSUE TITLE
2023年数据，补上吧

### ISSUE THREAD

**Issue by wuzhefang** [icyleaf/beijing-points-based-hukou#3]
https://github.com/jackfrued/python-100-days/blob/master/Day66-80/code/data/2023%E5%B9%B4%E5%8C%97%E4%BA%AC%E7%A7%AF%E5%88%86%E8%90%BD%E6%88%B7%E6%95%B0%E6%8D%AE.csv

**Comment by icyleaf** [comment]
感谢，已更新！
